name: Gatsby garden get

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:

      # Push event on branch lyz-code/blue-book
      - 'gatsby-digital-garden'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Number of commits to fetch. 0 indicates all history.
          # Default: 1
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
          architecture: x64
    
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install pip-tools

      - name: get gat
        run: gatsby new my-digital-garden https://github.com/omegakid1902/my-gatsby.git
