name: Gatsby garden get

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
  repository_dispatch:
    types: [update_zettelkasten]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install gatsby-cli
        run: |
          npm -v
          npm install -g gatsby-cli

      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GATSBY_SECRET }}
          deploy-branch: gh-pages
          git-config-name: 'github-actions[bot]'
          git-config-email: 'github-actions[bot]@users.noreply.github.com'

      - name: Alert repository_dispatch to omegakid1902.github.io repo
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.GATSBY_SECRET }}
          repo: omegakid1902.github.io
          owner: omegakid1902
          event_type: publish_gatsby_garden
