name: Gatsby garden get

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:

      # Push event on branch lyz-code/blue-book
      - 'gatsby-digital-garden'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Install gatsby-cli
        run: |
          npm -v
          npm install -g gatsby-cli
      
      - name: remove, get gat
        run: |
          cd ..
          rm -rf omegakid1902.github.io
          ls
          gatsby new omegakid1902.github.io https://github.com/omegakid1902/my-gatsby.git
          cd omegakid1902.github.io
          git remote set-url origin https://github.com/omegakid1902/omegakid1902.github.io.git

      - name: pwd
        run: pwd

      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.gatsby_secret }}
          deploy-branch: gh-pages-gatsby-digital-garden
          git-config-name: 'github-actions[bot]'
          git-config-email: 'github-actions[bot]@users.noreply.github.com'